# Numpy

In [11]:
#import Numpy Library

import numpy as np
from numpy import random

In [4]:
#create simple array from the list

arr = np.array([[1,22,333,4444],[54,65,76,87]])
arr

array([[   1,   22,  333, 4444],
       [  54,   65,   76,   87]])

In [5]:
arr.ndim #dimention

2

In [6]:
arr.shape #shape of array

(2, 4)

In [7]:
type(arr)

numpy.ndarray

In [10]:
arr.data #memory location

# Random Number Generator using numpy

In [22]:
x = random.randint(1000)
x

191

In [23]:
x = random.rand(7)
x

array([0.7083476 , 0.67051568, 0.98015219, 0.19983178, 0.44635103,
       0.31838538, 0.49543525])

In [24]:
x = random.randint(100, size=(5))
x

array([17,  9, 74, 79,  7])

In [25]:
x = random.randint(100, size=(5,4))
x

array([[83, 63, 60, 18],
       [34,  8, 37, 10],
       [58, 47, 85, 78],
       [ 5,  8, 36, 68],
       [15, 95, 61, 55]])

In [29]:
#a=1D array, with 7 integer
#b=1D array, with 7 integer
#math operation.

a = random.randint(50, size=(7))
print("a =",a)
b = random.randint(50, size=(7))
print("b =",b)

c = a + b
print("c =",c)

a = [19 35 17 38 15 42 12]
b = [25  3 21 26 22 30 13]
c = [44 38 38 64 37 72 25]


# Matrix in Numpy

In [30]:
a = np.matrix('1 2;3 4')
a

matrix([[1, 2],
        [3, 4]])

In [31]:
type(a)

numpy.matrix

In [33]:
b = np.matrix('1 2 3;4 5 6;7 8 9')
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
c = np.matrix([[5, 6, 7], [4, 8 ,3]])
c

matrix([[5, 6, 7],
        [4, 8, 3]])

# Measure of Central Tendency

In [39]:
arr = np.array([[1,22,33], [5,65,87], [5,6,2]])
arr

array([[ 1, 22, 33],
       [ 5, 65, 87],
       [ 5,  6,  2]])

In [40]:
#minimum value in array

np.amin(arr)

1

In [41]:
#maximum value in array

np.amax(arr)

87

In [43]:
#mean value in array

np.mean(arr)

25.11111111111111

In [44]:
#median value in array

np.median(arr)

6.0

In [45]:
#standard deviation value in array

np.std(arr)

29.40689429536491

In [47]:
#variance value in array

np.var(arr)

864.7654320987654